[build]
  command = "ng build"
  publish = "dist/angular-quickstart"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = [
    "/opt/build/repo/netlify/functions/Templates/adminTemp.html",
    "/opt/build/repo/netlify/functions/Templates/userTemp.html"
  ]
